#!/bin/sh
# Disable quotas

source `dirname $0`/quotas.config
source `dirname $0`/common

##################################################################

# reset quotas
`dirname $0`/reset_quotas

# reset tc
tc qdisc del dev $if_lan root

# reset iptables
for f in filter nat mangle; do
 iptables -t $f -F
 iptables -t $f -X
 iptables -t $f -F
done

iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT

iptables -t nat -A POSTROUTING -o $if_wan -j MASQUERADE

# destroy ipset
ipset destroy IP_QUOTA  2>/dev/null
