#!/bin/sh
# Disable quotas

die()   {  echo "$@"; exit 1;  }
config=`dirname $0`/quotas.config
[ -f "$config" ] || die "quotas.config missing"
source "$config"

##################################################################

# reset quotas
`dirname $0`/reset_quotas

# reset tc
tc qdisc del dev $if_lan root

# reset iptables
for f in filter nat mangle; do
 iptables -t $f -F
 iptables -t $f -X
 iptables -t $f -F
done

iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT

iptables -t nat -A POSTROUTING -o $if_wan -j MASQUERADE

# destroy ipsets
ipset destroy IP_QUOTA  2>/dev/null
for b in `seq 0 7`; do
    ipset destroy IPS_BIT$b  2>/dev/null
done
