#!/bin/sh
# Fixed download quotas per ip, cap download once over quota

# download quota (Mb)
dl_quota_mb=150
dl_quota=$(($dl_quota_mb * 1024 * 1024))

# max download speed (k/s)
dl_cap_max_kb=100
dl_cap_max=$(($dl_cap_max_kb * 8))

# max download speed once over quota (k/s)
dl_cap_kb=50
dl_cap=$(($dl_cap_kb * 8))

# lan addresses to limit (make sure it includes dhcp range)
lan=192.168.1
ip_start=100
ip_end=249

# lan interface
if=br-lan		# openwrt

indexes() { seq $ip_start $ip_end; }
run() { echo "$@"; if ! "$@"; then echo "failed !"; fi  }

#######################################################################

# reset tc / iptables
run `dirname $0`/disable_quotas

#######################################################################
# Rate limit

insmod sch_htb
insmod sch_sfq
insmod cls_fw

TCA="tc class add dev $if"
TFA="tc filter add dev $if"
TQA="tc qdisc add dev $if"
SFQ="sfq perturb 10"

run $TQA root handle 1: htb
for i in `indexes`; do
    id=$i
    # over quota speed limits
    run $TCA parent 1: classid 1:$id htb rate ${dl_cap}kbit ceil ${dl_cap}kbit prio 2
    run $TQA parent 1:$id handle $id: $SFQ
    run $TFA parent 1:0 prio 2 protocol ip handle $id fw flowid 1:$id

    id=$(( $i + 1000 ))
    # normal speed limits
    run $TCA parent 1: classid 1:$id htb rate ${dl_cap_max}kbit ceil ${dl_cap_max}kbit prio 2
    run $TQA parent 1:$id handle $id: $SFQ
    run $TFA parent 1:0 prio 2 protocol ip handle $id fw flowid 1:$id
done

#######################################################################
# Quota

insmod nfnetlink
insmod ip_set
insmod ip_set_hash_ip
insmod xt_set

# create ipset for accounting, no timeout
run ipset create IP_QUOTA hash:ip counters

IPT="iptables -t mangle -A POSTROUTING -o $if"

# if ip doesn't exist in the set, add it
run $IPT -m set ! --match-set IP_QUOTA dst -j SET --add-set IP_QUOTA dst

# set mark for regular download limit, 
# if over quota, set mark for hard speed limit
for i in `indexes`; do
    run $IPT --dst $lan.$i -j MARK --set-mark $(( $i + 1000 ))
    run $IPT --dst $lan.$i -m set --match-set IP_QUOTA dst --bytes-gt $dl_quota -j MARK --set-mark $i
done
