#!/bin/sh

source /etc/download_quotas.conf
source /usr/share/download_quotas/common

check_flag()
{
    v=`get_config "$global_section.$1"`
    [ "$v" =  "1" ] && echo '<span style="color:green">Yes</span>'
    [ "$v" != "1" ] && echo 'No'
}

if [ -f $status_file ]; then
    echo '<p style="font-size:small;">'
    echo "Version: " `opkg list_installed download-quotas | sed -e 's/.* //'` "<br>"
    echo 'Quotas: <span style="color:green">Enabled</span><br>'
    echo "Download quota per device: $dl_quota_mb Mb<br>"
    echo "Max download speed: $dl_cap_max_kb k/s (overquota: $dl_cap_kb k/s)<br>"
    echo "<br>"
    echo "Metered wifi: `check_flag metered_wifi`<br>"
    echo "Block android updates: `check_flag block_android_updates`<br>"
    echo "Disable at night: `check_flag night_disable`"
    echo "</p>"
else
    echo '<p>Quotas: <span style="color:red">Disabled</span></p>'
fi

echo '<pre>'
echo ""; echo ""

/etc/init.d/download-quotas list

echo '</pre>'
