#!/bin/sh
# update script: download and install another version
# usage: install remote_repo_file.ipk

get_config()       {  uci -q get "$1";  }
repo_url=`get_config "download_quotas.@other[0].repo_url"`

file=`basename "$1"`
mkdir /tmp/downloads  2>/dev/null
cd /tmp/downloads

/usr/bin/wget --no-check-certificate -O "$file" "$repo_url/$1"  || exit 1
tar -tvzf "$file" > /dev/null                          || exit 1
tar -tvzf "$file" | grep -q control.tar.gz             || exit 1
opkg remove download-quotas                            || exit 1
opkg install "$file"                                   || exit 1
