#!/bin/sh
# Disable quotas

source /etc/download_quotas.conf
source /usr/share/download_quotas/common

# not checking $status_file here

##################################################################

# reset quotas
`dirname $0`/reset_quotas

# remove status file
rm $status_file

# reset tc
tc qdisc del dev $if_lan root

# reset iptables
for f in filter nat mangle; do
 iptables -t $f -F
 iptables -t $f -X
 iptables -t $f -F
done

iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT

iptables -t nat -A POSTROUTING -o $if_wan -j MASQUERADE

# destroy ipset
ipset destroy IP_QUOTA  2>/dev/null

#######################################################################
# Other settings

echo "Stopping metered wifi"
/usr/share/download_quotas/luci/update_metered stop
