#!/bin/sh
# Fixed download quotas per ip, cap download once over quota

config=/etc/download_quotas.conf
source $config
source /usr/share/download_quotas/common

[ -f $status_file ] && die "download quotas already enabled"

check_interface "$if_lan" || die "$config: interface $if_lan doesn't exist !"
check_interface "$if_wan" || die "$config: interface $if_wan doesn't exist !"
lan_current=`ifconfig $if_lan | grep 'inet addr' | sed -e 's/.*:\([^ ]*\) .*/\1/' | cut -d. -f1-3 `
[ "$lan" = "$lan_current" ] || die "$config: lan=$lan  should be $lan_current"

echo "--------------------------------------------------------------------------------"
echo "setting up download quotas: $dl_quota_mb Mb"
echo "limiting downloads to $dl_cap_max_kb k/s (overquota: $dl_cap_kb k/s)"
echo "for ips in [ $lan.$ip_start - $lan.$ip_end ] on interface $if_lan"
echo "--------------------------------------------------------------------------------"
echo ""

#######################################################################
# reset tc / iptables
echo "resetting tc iptables and ipset"
`dirname $0`/disable_quotas

#######################################################################
# tc: create classes for each ip

insmod sch_htb
insmod sch_sfq
# insmod cls_fw       # could remove now

TCA="tc class add dev $if_lan"
TQA="tc qdisc add dev $if_lan"
SFQ="sfq perturb 10"

run $TQA root handle 1: htb
for i in `ip_indexes`; do
    printf "creating tc classes for $lan.$i\r"
    id=$i
    # over quota speed limits
    $TCA parent 1: classid 1:$id htb rate ${dl_cap}kbit ceil ${dl_cap}kbit prio 2
    $TQA parent 1:$id handle $id: $SFQ

    id=$(($i + 512))
    # normal speed limits
    $TCA parent 1: classid 1:$id htb rate ${dl_cap_max}kbit ceil ${dl_cap_max}kbit prio 2
    $TQA parent 1:$id handle $id: $SFQ
done
echo ""

#######################################################################
# ipset

insmod nfnetlink
insmod ip_set
insmod ip_set_bitmap_ip

# create ipset for accounting, no timeout
run ipset create IP_QUOTA bitmap:ip range $lan.0/24 counters
run ipset add IP_QUOTA $lan.0/24

#######################################################################
# iptables: check quotas and classify packets

insmod xt_set
insmod xt_CLASSIFY
insmod xt_string
insmod ts_bm

IPT="iptables -t mangle"
IPT_POST="iptables -t mangle -A POSTROUTING -o $if_lan"

run $IPT -N normal
run $IPT -N overquota
run $IPT_POST -m set --match-set IP_QUOTA dst --bytes-gt $dl_quota -g overquota
run $IPT_POST -m set --match-set IP_QUOTA dst ! --update-counters -g normal

block_https()
{
    run iptables -t filter -A FORWARD -i $if_lan -p tcp --dport 443 -m string --algo bm --string "$1" -j REJECT
}

block_android=`get_config "$global_section.block_android_updates"`
if [ "$block_android" = "1" ]; then
    echo "blocking android updates"
    block_https "play.googleapis.com"
    block_https "android.clients.google.com"
    block_https "lh3.googleusercontent.com"
fi

# classify packets
for i in `ip_indexes`; do
    printf "creating iptables rules for $lan.$i\r"
    $IPT -A overquota --dst $lan.$i -j CLASSIFY --set-class 1:$i
    $IPT -A normal    --dst $lan.$i -j CLASSIFY --set-class 1:$(($i + 512))
done
echo ""

touch $status_file

#######################################################################
# Other settings

# metered wifi
/usr/share/download_quotas/luci/update_metered

echo "done !"
