#!/bin/sh
# Show quota usage

source /usr/share/download_quotas/common

[ -f $status_file ] || die "download quotas are disabled"

print_quota()
{
    mac="$1";  bytes="$2";  time="$3";  name="$4"
    mb=$(( $bytes / (1024 * 1024) ))
    hk=$(( ($bytes % (1024 * 1024)) / (100 * 1024) ))
    printf "  %5i.$hk Mb  %-35s $mac $time\n" "$mb" "$name"
}

echo ""
echo "Quota usage:"
`dirname $0`/save_quotas - | tail +2 | tr ' '  '\n' |
while read mac; read bytes; read timestamp; read name; do
    time=`date -I --date=@$timestamp`
    print_quota "$mac" "$bytes" "$time" "$name"
done
echo ""
