#!/bin/sh
# Show quota usage

source /usr/share/download_quotas/common

[ -f $status_file ] || die "download quotas are disabled"

print_quota()
{
    mac="$1";  bytes="$2";  time="$3";  name="$4";  ip="$5"
    mb=$(( $bytes / (1024 * 1024) ))
    hk=$(( ($bytes % (1024 * 1024)) * 10 / (1024 * 1024) ))
    printf "%-15s %5i.$hk Mb  %-39s $time          $mac\n"  "$ip"  "$mb"  "$name"
}

# busybox sort -k doesn't work, beware
sort_by_timestamp() {  awk '{print $3" "$1" "$2" "$4;}' | sort -n | awk '{print $2" "$3" "$1" "$4;}';  }

# return ip(s) found for mac
ips_for_mac() {  < /proc/net/arp grep -F "$1" | cut -d' ' -f1 ;  }

echo "Current IP        Usage     Name                                    Last Seen                 Mac Address"

`dirname $0`/save_quotas - | tail +2 | sort_by_timestamp | tr ' '  '\n' |
while read mac; read bytes; read timestamp; read name; do
    time=`date --date=@$timestamp +"%Y-%m-%d %H:%M"`
    first=1
    for ip in `ips_for_mac $mac` ""; do
	if [ -n "$first" ] || [ -n "$ip" ]; then
	    print_quota "$mac" "$bytes" "$time" "$name" "$ip";   first=""
	fi
    done
done

