#!/bin/sh
# load quotas

source /etc/download_quotas.conf
source /usr/share/download_quotas/common

[ -f $status_file ] || die "download quotas are disabled"

usage() {  die "usage: load_quotas file";  }
[ -f "$1" ] || usage

h=`head -1 "$1"`
[ "$h" = "$header" ] || die "invalid file"

####################################################################################

#echo "restoring mac quotas ..."
tail +2 "$1" > $mac_counters

####################################################################################

#echo ""
#echo "restoring ip quotas ..."
ipset flush IP_QUOTA 
parse_arp | list_arp | while read ip ; read mac; do
    quota=`grep -F $mac < "$1" | cut -d' ' -f2 `
    [ -z "$quota" ] && continue
    #echo "  $ip -> $quota" 1>&2
    echo "add IP_QUOTA $ip packets 0 bytes $quota"
done | ipset restore 

