#!/bin/sh

source /usr/share/download_quotas/common

[ -f $status_file ] || die "download quotas are disabled"

ipset flush IP_QUOTA  2>/dev/null

rm $mac_counters  2>/dev/null
rm $saved_arp  2>/dev/null
