#!/bin/sh
# Save quotas to stdout

source /etc/download_quotas.conf
source /usr/share/download_quotas/common

[ -f $status_file ] || die "download quotas are disabled"

file="$1"
[ "$file" = "-" ] && file="/proc/$$/fd/1"

usage() {  die "usage: save_quotas file";  }
[ -n "$file" ] || usage

####################################################################################

echo "$header" > "$file"

timestamp=`date +"%s"`
dump_online_quotas()
{
    ip_counters | tr ' '  '\n' | while read ip; read bytes; do
	mac=`mac_for_ip $ip`
	[ -z "$mac" ] && continue
	name=`host_name $ip`
	[ -z "$name" ] && name=`name_for_mac $mac`
	echo "$mac" "$bytes" "$timestamp" "$name"
    done    
}

dump_offline_quotas() {  cat $mac_counters 2>/dev/null;  }

####################################################################################
# merge online / offline quotas  (keep highest)

AWK_MERGE_QUOTAS='
  {
        if (bytes[$1] < $2) { bytes[$1]=$2; }
        timestamp[$1]=$3;  name[$1]=$4;
  }
  END{  
        for(mac in bytes) { print mac " " bytes[mac] " " timestamp[mac] " " name[mac]; }  
  }
'

(  dump_offline_quotas;  dump_online_quotas  ) | awk "$AWK_MERGE_QUOTAS" >> "$file"
