#!/bin/sh
# Show current/saved quota usage

print_quota()
{
    bytes="$1";  ip="$2";  mac="$3";  name="$4";
    mb=$(( $bytes / (1024 * 1024) ))
    hk=$(( ($bytes % (1024 * 1024)) / (100 * 1024) ))
    printf "  %-15s  %5i.$hk Mb  %-40s %s\n" "$ip" "$mb" "$name" "$mac"
}

echo ""
echo "Quota usage (saved):"
cat /tmp/mac_counters | tr ' '  '\n' |
while read mac; read bytes; do
    print_quota "$bytes" "" "$mac" ""
done

echo ""
echo "Quota usage (currently used):"
ipset save IP_QUOTA | grep -vF 255.255.255.255 | grep add | cut -d' ' -f3,7 | tr ' '  '\n' |
while read ip; read bytes; do
    mac=`cat /proc/net/arp | grep -F $ip | sed -e 's/  */ /g' | cut -d' ' -f4`
    name=`nslookup $ip | tail -1 | cut -d' ' -f4-`
    print_quota "$bytes" "$ip" "$mac" "$name"
done
echo ""
